# Generated by Django 5.2.12 on 2026-06-24 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="failure_alerts",
                to="notifications.notification",
            ),
        ),
    ]
