
# Generated by Django 5.2.12 on 2026-06-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="veterinarian_bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="veterinarian_license_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="veterinarian_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
