# Generated by Django 5.2.12 on 2026-06-07 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_appointment"),
        ("pets", "0002_remove_petowner_address_petowner_address_line_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_date", models.DateField()),
                ("diagnosis", models.TextField(blank=True)),
                ("symptoms", models.TextField(blank=True)),
                ("treatment_given", models.TextField(blank=True)),
                ("public_notes", models.TextField(blank=True)),
                ("private_notes", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_record",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_medical_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "ordering": ["-record_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100)),
                ("dosage", models.CharField(blank=True, max_length=100)),
                ("frequency", models.CharField(blank=True, max_length=100)),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_items",
                        to="medical.medicalrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestResultFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="test_results/")),
                ("description", models.CharField(blank=True, max_length=100)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_result_files",
                        to="medical.medicalrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vaccine_name",
                    models.CharField(
                        choices=[
                            ("Deworming", "Deworming"),
                            ("Ivermectin", "Ivermectin"),
                            ("Anti-rabies", "Anti-rabies"),
                            ("6-in-1", "6-in-1"),
                            ("7-in-1", "7-in-1"),
                            ("8-in-1", "8-in-1"),
                            ("Bordetella", "Bordetella"),
                            ("Other", "Other (specify below)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("custom_vaccine_name", models.CharField(blank=True, max_length=100)),
                ("date_administered", models.DateField()),
                (
                    "weight_at_vaccination",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("batch_number", models.CharField(blank=True, max_length=50)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("administered_by", models.CharField(blank=True, max_length=100)),
                ("site_of_injection", models.CharField(blank=True, max_length=50)),
                ("is_corrected", models.BooleanField(default=False)),
                ("correction_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccinations",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccinations",
                        to="medical.medicalrecord",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_administered"],
            },
        ),
    ]
