# Generated by Django 5.2.12 on 2026-06-20 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Condition name, e.g. Bordetella", max_length=100
                    ),
                ),
                ("description", models.TextField(help_text="General overview")),
                ("causes", models.TextField(blank=True)),
                ("symptoms", models.TextField(blank=True)),
                (
                    "general_care",
                    models.TextField(blank=True, help_text="Treatment guidance"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Unpublished articles are hidden from pet owners.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
